/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the <dlfcn.h> header file. */
#define HAVE_DLFCN_H 1

/* Define to 1 if you have the <getopt.h> header file. */
#define HAVE_GETOPT_H 1

/* Define to 1 if you have the `getopt_long' function. */
#define HAVE_GETOPT_LONG 1

/* Define to 1 if you have the <inttypes.h> header file. */
#define HAVE_INTTYPES_H 1

/* Define to 1 if you have the <memory.h> header file. */
#define HAVE_MEMORY_H 1

/* Define to 1 if you have the <stdint.h> header file. */
#define HAVE_STDINT_H 1

/* Define to 1 if you have the <stdlib.h> header file. */
#define HAVE_STDLIB_H 1

/* Define to 1 if you have the <strings.h> header file. */
#define HAVE_STRINGS_H 1

/* Define to 1 if you have the <string.h> header file. */
#define HAVE_STRING_H 1

/* Define to 1 if you have the <sys/stat.h> header file. */
#define HAVE_SYS_STAT_H 1

/* Define to 1 if you have the <sys/types.h> header file. */
#define HAVE_SYS_TYPES_H 1

/* Define to 1 if you have the <unistd.h> header file. */
#define HAVE_UNISTD_H 1

/* action debugging output */
/* #undef KEY_ACTION_DEBUG */

/* ClassBasedTest.cpp */
/* #undef KEY_CLASS_BASED_TESTING */

/* parser sentry output */
/* #undef KEY_P_SENTRY */

/* symbol table sentry output */
/* #undef KEY_ST_SENTRY */

/* btyacc debugging output */
/* #undef KEY_YACC_DEBUG */

/* Name of package */
#define PACKAGE "keystone"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "keystone@cs.clemson.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "keystone"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "keystone 0.2.3"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "keystone"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.2.3"

/* Define to 1 if you have the ANSI C header files. */
#define STDC_HEADERS 1

/* Version number of package */
#define VERSION "0.2.3"

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
/* #undef YYTEXT_POINTER */
