# mkfieldcnt.sh, 24 Feb 13
#
# Extract data from various .met files (generated by mcc -met)
# needed for C construct frequency tables

source ../config.files

GEN_DATA="0"

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f fieldtype.awk > $LOC_TAB_DIR/fieldtype
   fi

#zcat *$MET_SUFF | awk -f fieldtype.awk > fieldtype

zcat *$MET_SUFF | awk -f fielduse.awk > fielduse

