# mktab.sh, 25 Sep 25
#
# Extract data from various .met files (generated by mcc -met)
# needed for C construct frequency tables

source ../config.files

#GEN_DATA="1"

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f arraytype.awk > $LOC_TAB_DIR/arraydims
   fi
awk -v D_FILE="array_dims" -f $EXTRTABLE < $LOC_TAB_DIR/arraydims > $GLOB_TAB_DIR/arraydims
zcat *$MET_SUFF | awk -f mkctype.awk -f elemtype.awk | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/elem_type
zcat *$MET_SUFF | awk -f mkctype.awk -f pointedto.awk | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/pointed_to_type
zcat *$MET_SUFF | awk -f qualifier.awk | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/qual_types
if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f selnest.awk > $LOC_TAB_DIR/selnest
   fi
awk -v D_FILE="seltable.d" -f $EXTRTABLE < $LOC_TAB_DIR/selnest > $GLOB_TAB_DIR/selnest
zcat *$MET_SUFF | awk -f numlabels.awk | $MKTWOCOL > $GLOB_TAB_DIR/numlabels

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f mkctype.awk -f objtype.awk > $LOC_TAB_DIR/objtype
   fi
awk -v D_FILE="param_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/objtype | $SORTLASTCOL | $MKFOURCOL > $GLOB_TAB_DIR/param_type
awk -v D_FILE="loc_obj_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/objtype | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/loc_obj_type
awk -v D_FILE="ext_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/objtype | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/ext_obj_type
awk -v D_FILE="int_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/objtype | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/int_obj_type
   
if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f mkctype.awk -f argtype.awk > $LOC_TAB_DIR/argtype
   zcat *$MET_SUFF | awk -f mkctype.awk -f rettype.awk > $LOC_TAB_DIR/rettype
   fi
cat $LOC_TAB_DIR/argtype | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/arg_type
cat $LOC_TAB_DIR/rettype | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/ret_type

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f mkctype.awk -f typedtype.awk > $LOC_TAB_DIR/typedef_type
   fi
awk -v D_FILE="typedef_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/typedef_type | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/typedef_type

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f mkctype.awk -f init.awk > $LOC_TAB_DIR/init
   fi
awk -v D_FILE="loc_init_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/init | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/loc_init_type
awk -v D_FILE="glob_init_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/init | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/glob_init_type

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f getidkind.awk > $LOC_TAB_DIR/getidkind
   zcat $MCC_DIR/*$MCC_SUFF | awk -f $MCC_DIR/macroid.awk >> $LOC_TAB_DIR/getidkind
   fi
awk -f idcase.awk < $LOC_TAB_DIR/getidkind > $GLOB_TAB_DIR/id_kind_case
awk -f namespace.awk < $LOC_TAB_DIR/getidkind | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/id_namespace

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f getidtype.awk > $LOC_TAB_DIR/getidtype
   fi
awk -v D_FILE="floating_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/getidtype > $GLOB_TAB_DIR/float_t_usage
awk -v D_FILE="character_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/getidtype > $GLOB_TAB_DIR/character_t_usage
awk -v D_FILE="integer_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/getidtype > $GLOB_TAB_DIR/integer_t_usage
awk -v D_FILE="derived_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/getidtype > $GLOB_TAB_DIR/derived_t_usage
awk -v D_FILE="type_qual.t" -f $EXTRTABLE < $LOC_TAB_DIR/getidtype > $GLOB_TAB_DIR/qual_context

if [ $GEN_DATA == 1 ]; then
   zcat *$MET_SUFF | awk -f mkctype.awk -f members.awk > $LOC_TAB_DIR/members
   fi
awk -v D_FILE="st_member_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/members | $SORTLASTCOL | $MKFOURCOL > $GLOB_TAB_DIR/st_member_type
awk -v D_FILE="un_member_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/members | $SORTLASTCOL | $MKFOURCOL > $GLOB_TAB_DIR/un_member_type

awk -v D_FILE="func_call_names.d" -f $EXTRTABLE < $LOC_DIA_DIR/calluse > $LOC_TAB_DIR/libcalls
cat libids.txt $LOC_TAB_DIR/libcalls | awk -f libcalls.awk | $SORTLASTCOL | $MKFOURCOL > $GLOB_TAB_DIR/lib_func_use

awk -v D_FILE="full_expr_per_func.t" -f $EXTRTABLE < $LOC_DIA_DIR/fdefinfo | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/full_expr_per_func

