# mktab.sh, 16 Dec 03
#
# Extract data from various files (generated by ngram)
# needed for C construct frequency tables

source ../config.files

awk -v D_FILE="esu_syntax.t" -f $EXTRTABLE < $LOC_DIA_DIR/esutag.h > $TEMP_FILE
echo "END_DOT_H" >> $TEMP_FILE
awk -v D_FILE="esu_syntax.t" -f $EXTRTABLE < $LOC_DIA_DIR/esutag.c >> $TEMP_FILE
$MERGE_C_H < $TEMP_FILE | $MKTWOCOL > $GLOB_TAB_DIR/esu_tok_tok

rm $TEMP_FILE
