#
# mktab.sh, 28 Sep 25
#
# Extract data from various files (generated by ngram)
# needed for C construct frequency tables

source ../config.files

pwd

#GEN_DATA=1

LOGICAL_OPS=" && || "
SHIFT_OPS=" >> << "
BITWISE_OPS=" & | ^ "
BIT_OPS=" ~ ^= <<= >>= &= |= $SHIFT_OPS $BITWISE_OPS"
MULT_OPS=" * / % "
ADD_OPS=" - + "
ASSIGN_OPS=" = += -= *= /= %= |= &= ^= <<= >>= "
ARITH_OPS=" += -= *= /= %= $MULT_OPS $ADD_OPS"
REL_OPS=" < <= > >= "
EQUAL_OPS=" == != "
POSTFIX_OPS=" . -> v++ v-- "				; export POSTFIX_OPS
PREFIX_OPS=" ++v --v "					; export PREFIX_OPS
UNARY_OPS=" cast sizeof &v *v +v -v ~ ! "		; export UNARY_OPS
TERNARY_OPS=" ?: "
RVALUE_OPS="$BIT_OPS $LOGICAL_OPS $ARITH_OPS $REL_OPS $EQUAL_OPS $UNARY_OPS"  ; export RVALUE_OPS
EXPR_OPS="$RVALUE_OPS $TERNARY_OPS $ASSIGN_OPS"		; export EXPR_OPS

if [ $GEN_DATA == 1 ]; then
   xzcat *.mcc.xz | awk -f funcall.awk > $LOC_TAB_DIR/fun_decl_call
   fi
cp $LOC_TAB_DIR/fun_decl_call $GLOB_TAB_DIR/fun_decl_call

if [ $GEN_DATA == 1 ]; then
   xzcat *.mcc.xz | awk -f impcast.awk > $LOC_TAB_DIR/impcast
   fi

awk -v D_FILE="int_promote" -f $EXTRTABLE < $LOC_TAB_DIR/impcast | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/int_promote
awk -v D_FILE="simp_to_from" -f $EXTRTABLE < $LOC_TAB_DIR/impcast | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/imp_conv
awk -f type_ops.awk -f impptr.awk < $LOC_TAB_DIR/impcast | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/imp_ptr

if [ $GEN_DATA == 1 ]; then
   xzcat *.mcc.xz | awk -f exprtype.awk > $LOC_TAB_DIR/exprops
   fi

awk -v OP_TOK="$LOGICAL_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/logical_oprnd
awk -v OP_TOK="$BITWISE_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/bitwise_oprnd
awk -v OP_TOK="$SHIFT_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/shift_oprnd
awk -v OP_TOK="$MULT_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/mult_oprnd
awk -v OP_TOK="$ADD_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/add_oprnd
awk -v OP_TOK="$REL_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/rel_oprnd
awk -v OP_TOK="$EQUAL_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/equal_oprnd
awk -v OP_TOK="$TERNARY_OPS" -f exprops.awk < $LOC_TAB_DIR/exprops | awk -f ternary.awk | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/ternary_oprnd
awk -v OP_TOK="$ASSIGN_OPS" -v OP_FREQ="2.3" -f exprops.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/assign_oprnd

awk -f type_ops.awk -f eqptr.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/equal_ptr_oprnd
awk -f type_ops.awk -f relptr.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/rel_ptr_oprnd
awk -f type_ops.awk -f addsubptr.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/addsub_ptr_oprnd
awk -f type_ops.awk -f subptr.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/sub_ptr_oprnd
awk -f type_ops.awk -f castop.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/cast_oprnd
awk -f type_ops.awk -f sizeofop.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/sizeof_oprnd
awk -f type_ops.awk -f unaryop.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTHREECOL > $GLOB_TAB_DIR/unary_oprnd
awk -f type_ops.awk -f postfixop.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/postfix_oprnd

awk -v D_FILE="enum_const_role.t" -f $EXTRTABLE < $LOC_DIA_DIR/ecvals > $GLOB_TAB_DIR/enum_const_role

if [ $GEN_DATA == 1 ]; then
   xzcat *.mcc.xz | awk -f mkctype.awk -f switch.awk > $LOC_TAB_DIR/switch
   fi
awk -v D_FILE="switch_cntrl_type.t" -f $EXTRTABLE < $LOC_TAB_DIR/switch | $SORTLASTCOL | $MKTWOCOL > $GLOB_TAB_DIR/switch_cntrl_type

#rm $TEMP_FILE
