# mktab.sh, 29 Dec 03
#
# Extract data from various files (generated by ngram)
# needed for C construct frequency tables

source ../config.files

pwd

#GEN_DATA=1

LOGICAL_OPS=" && || "
SHIFT_OPS=" >> << "
BITWISE_OPS=" & | ^ "
BIT_OPS=" ~ ^= <<= >>= &= |= $SHIFT_OPS $BITWISE_OPS"
MULT_OPS=" * / % "
ADD_OPS=" - + "
ASSIGN_OPS=" = += -= *= /= %= |= &= ^= <<= >>= "
ARITH_OPS=" += -= *= /= %= $MULT_OPS $ADD_OPS"
REL_OPS=" < <= > >= "
EQUAL_OPS=" == != "
POSTFIX_OPS=" . -> v++ v-- "				; export POSTFIX_OPS
PREFIX_OPS=" ++v --v "					; export PREFIX_OPS
UNARY_OPS=" cast sizeof &v *v +v -v ~ ! "		; export UNARY_OPS
TERNARY_OPS=" ?: "
RVALUE_OPS="$BIT_OPS $LOGICAL_OPS $ARITH_OPS $REL_OPS $EQUAL_OPS $UNARY_OPS"  ; export RVALUE_OPS
EXPR_OPS="$RVALUE_OPS $TERNARY_OPS $ASSIGN_OPS"		; export EXPR_OPS

awk -f type_ops.awk -f unaryop.awk < $LOC_TAB_DIR/exprops | $SORTLASTCOL | $MKTHREECOL > $GLOB_TAB_DIR/unary_oprnd
